version: "3"

services:

  mongo-db:
    image: mongo:4.4
    command: --nojournal

  orion:
    image: fiware/orion
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG

  crate:
    image: crate:4.2.7
    hostname: crate-db
    ports:
      - "4200:4200"
      - "4300:4300"
      - "5432:5432"
    command:
      - crate
      - -Cauth.host_based.enabled=false
      - -Ccluster.name=ndn-sensor-cluster
      - -Chttp.cors.enabled=true
      - -Chttp.cors.allow-origin="*"
    environment:
      - CRATE_HEAP_SIZE=2g

  quantumleap:
    image: orchestracities/quantumleap:edge
    hostname: quantumleap
    ports:
      - "8668:8668"
    depends_on:
      - orion
      - crate
    environment:
      - LOGLEVEL=DEBUG
      - CRATE_HOST=crate
#      - QL_DEFAULT_DB=timescale
#      - POSTGRES_HOST=timescale
#      - POSTGRES_DB_PASS=*
#      - POSTGRES_DB_USER=postgres
#      - POSTGRES_DB_NAME=postgres

  grafana:
    image: grafana/grafana
    depends_on:
      - crate
    ports:
      - "3003:3000"
    environment:
      - GF_INSTALL_PLUGINS=orchestracities-map-panel,grafana-clock-panel,grafana-worldmap-panel

#  ld-context:
#    image: httpd:alpine
#    hostname: context
#    container_name: fiware-ld-context
#    ports:
#      - "3000:80"
#    volumes:
#      - "C:/Users/arne-/Downloads:/usr/local/apache2/htdocs"

#  quantumleap-init:
#    image: orchestracities/quantumleap-pg-init
#    depends_on:
#      - timescale
#      - quantumleap
#    environment:
#      - QL_DB_PASS=*
#      - QL_DB_INIT_DIR=/ql-db-init
#      - PG_HOST=timescale
#      - PG_PASS=*

  # http://localhost:4000/mockserver/dashboard
#  mock-server:
#    image: mockserver/mockserver
#    hostname: mockserver
#    ports:
#      - "4000:1080"

volumes:
  grafana-storage: { }